import type { Metadata } from "next";
import { Lato, Marcellus } from "next/font/google";
import "./globals.css";

// Lato → Sans
const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
});

// Marcellus → Serif
const marcellus = Marcellus({
  variable: "--font-mar",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Cs-Design-Studio",
  description: "Generated by create next app",
  icons: {
    icon: "/csdesign-icon.jpg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${lato.variable} ${marcellus.variable}`}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
